### ISSUE TITLE
Problem with mysql

### ISSUE THREAD

**Issue by honzajan123** [scruffyboy13/Economy#2]
Hello, I setup your plugin to mysql and now, it probably works, BUT
If i set money to player on server1, its okay, but if i go to server2, i dont have the same money value.
If i do restart, then it make same values, but, again if i set money on one server, it doesnt apply to another server until restart..

Thank you for quick respond.

**Comment by scruffyboy13** [comment]
Hi, so the economy plugin isn't currently made for working on multiple servers at the same time. This will be added when I find the time to do so.
