### ISSUE TITLE
Show symbol after the amount of money

### ISSUE THREAD

**Issue by bakaschwarz** [scruffyboy13/Economy#3]
It would be awesome, if you could specify with maybe a `symbol-after-amount: true/false` option to have the
symbol shown after an amount in messages.
My server uses Gold oder G as currency and i try to show prices in shop etc. like so: 1G, 500G, 1377G and so on.
When we use the `/money` commands it is shown like so: G1, G100, G1377 which looks a bit off.
Having an option to set the placement would be wonderful!

Thank you for this plugin!

**Comment by scruffyboy13** [comment]
So the problem with that is that to format the balance, you choose a locale. Different locales have symbols at different points so I can't control where to put the symbol. e.g. for fr-FR (France) the € is at the end of the string whereas in en-US (USA) the $ is at the start
